# Generated by Django 5.1.7 on 2025-03-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название организации",
                        max_length=255,
                        unique=True,
                        verbose_name="Название организации",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите email", max_length=254, unique=True, verbose_name="Email адрес"
                    ),
                ),
                ("country", models.CharField(help_text="Введите страну", max_length=100, verbose_name="Страна")),
                ("city", models.CharField(help_text="Введите город", max_length=100, verbose_name="Город")),
                (
                    "street",
                    models.CharField(
                        blank=True, help_text="Введите улицу", max_length=100, null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, help_text="Введите номер дома", max_length=10, null=True, verbose_name="Номер дома"
                    ),
                ),
                (
                    "hierarchy_level",
                    models.CharField(
                        choices=[("0", "0"), ("1", "1"), ("2", "2")],
                        help_text="Укажите уровень иерархии",
                        verbose_name="Уровень иерархии сети",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now=True, verbose_name="Время создания")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="business.company",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название продукта", max_length=255, verbose_name="Название продукта"
                    ),
                ),
                (
                    "model",
                    models.CharField(help_text="Введите модель продукта", max_length=255, verbose_name="Модель"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату выхода продукта на рынок",
                        null=True,
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="business.company")),
            ],
        ),
    ]
